name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g appium
          appium driver update uiautomator2

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator (Background)
        run: |
          nohup emulator -avd pixel_3a -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim > emulator.log 2>&1 &
          echo "Emulator started in background."

      - name: Wait for Emulator Boot Confirmation
        run: |
          echo "Waiting for emulator to fully boot..."
          max_attempts=30
          attempt=0
          while [[ $(adb shell getprop sys.boot_completed 2>/dev/null) != "1" && $attempt -lt $max_attempts ]]; do
            echo "Waiting... Attempt: $attempt"
            sleep 5
            ((attempt++))
          done
          if [[ $(adb shell getprop sys.boot_completed 2>/dev/null) != "1" ]]; then
            echo "Emulator failed to start in time"
            exit 1
          fi
          echo "Emulator booted successfully!"

          # Garantindo que o emulador está 100% pronto antes de interagir
          sleep 10

          # Desbloquear a tela
          adb shell input keyevent 82

          # Desativar animações
          adb shell settings put global window_animation_scale 0.0 || true
          adb shell settings put global transition_animation_scale 0.0 || true
          adb shell settings put global animator_duration_scale 0.0 || true

      - name: Run WebdriverIO Tests
        run: npx wdio wdio.conf.js

      - name: Stop Emulator
        if: always()
        run: adb emu kill || true
