name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g appium
          appium driver update uiautomator2

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator and Monitor Boot
        run: |
          # Inicia o emulador em background
          nohup emulator -avd pixel_3a -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &

          # Aguarda a mensagem "Emulator booted."
          echo "Waiting for emulator to fully boot..."
          while true; do
            BOOTED=$(adb shell getprop sys.boot_completed 2>/dev/null)
            if [[ "$BOOTED" == "1" ]]; then
              echo "Emulator booted."
              break
            fi
            sleep 5
          done

      - name: Run WebdriverIO Tests
        run: npx wdio wdio.conf.js &

      - name: Stop Emulator
        if: always()
        run: adb emu kill
        