name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g appium
          appium driver update uiautomator2

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          disable-animations: true
          emulator-options: "-no-window -gpu swiftshader_indirect -noaudio -no-boot-anim"
          script: adb devices

      - name: Wait for Emulator to be Ready
        run: |
          max_attempts=30
          attempt=0
          while [[ $(adb shell getprop sys.boot_completed 2>/dev/null) != "1" && $attempt -lt $max_attempts ]]; do
            echo "Waiting for emulator to be ready... Attempt: $attempt"
            sleep 5
            ((attempt++))
          done
          if [[ $(adb shell getprop sys.boot_completed 2>/dev/null) != "1" ]]; then
            echo "Emulator failed to start in time"
            exit 1
          fi
          echo "Emulator is ready!"

      - name: Keep ADB Connection Alive
        run: |
          nohup adb logcat > /dev/null 2>&1 &
          echo "ADB logcat process started in the background."

      - name: Run WebdriverIO Tests
        run: npx wdio wdio.conf.js

      - name: Stop Emulator
        if: always()
        run: adb emu kill
